# Generated by Django 4.2.6 on 2023-10-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custonuser',
            old_name='Profiles',
            new_name='profiles',
        ),
    ]
